# SCIKIT LEARN - STANDARD SCALER

$$z = \frac{(x - \bar{x})}{\sigma}$$
$$\sigma = \sqrt{\frac{\sum_{i=1}^{n} (x_{i} - \bar{x})^{2}}{n}}$$

In [2]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# Sample data
data = np.array([[10], [20], [30], [40], [50]])
print("Original Data:")
print(data)

Original Data:
[[10]
 [20]
 [30]
 [40]
 [50]]


El método **fit_transform** calcula la media y la desviación estándar de los datos y luego los transforma para que tengan media cero y varianza unitaria (desviación estándar de 1).

In [7]:
# Estandarizar / Normalizar los datos
scaler = StandardScaler()
standardized_data = scaler.fit_transform(data)
print(f"Standardized Data:\n {standardized_data}")

# Estandarizar los datos manualmente
mean = np.mean(data)
std_dev = np.std(data)
standardized_data = (data - mean) / std_dev
print(data - mean)
print(f"nMean: {mean}")
print(f"Standard Deviation: {std_dev}")
print(f"Standardized Data:\n {standardized_data}")

Standardized Data:
 [[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]
[[-20.]
 [-10.]
 [  0.]
 [ 10.]
 [ 20.]]
nMean: 30.0
Standard Deviation: 14.142135623730951
Standardized Data:
 [[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [ ]:
# Resumen
df_result = pd.DataFrame({
    'x': data,
    'mena': y_pred,
    'y_pred_poly': y_pred_poly
})
print(df_result)